name: Release

# https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    # https://github.com/actions/setup-python/issues/544
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup python 
      uses: actions/setup-python@v4
      with: 
        python-version: '3.8' 
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build releases
      working-directory: ./scripts/release
      run: |
        ./pre-build.sh
        ./build-client-go.sh
        ./build-client-py.sh
        ./build-server-py.sh


    - name: Publish GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/*
        token: ${{ secrets.GITHUB_TOKEN }}
